options:
  logging: CLOUD_LOGGING_ONLY

steps:

- name: 'docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image', '.']

# Authenticate kubectl - Get credentials for GKE cluster
- name: 'gcloud'
  entrypoint: 'bash'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=devops-playground'
  - 'CLOUDSDK_PROJECT=$PROJECT_ID'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials devops-playground --zone us-central1-c

# Set the Kubernetes cluster context
- name: 'kubectlcontext'
  args:
    - 'config'
    - 'use-context'
    - 'gke_us-central1-c_devops-playground'

# Use kubectl for all subsequent Kubernetes operations, each in its own step
- name: 'namespace'
  args: ['create', 'namespace', 'kloud-ns']

# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'deployment.yaml', '-n', 'my-namespace']


images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image' 




